/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package managecoffeechain;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.Image;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import models.OrderProductResult;
import models.Product;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PiePlot;
import org.jfree.data.general.DefaultPieDataset;
import services.OrderProductService;
import services.OrderService;
import services.ProductService;

/**
 *
 * @author thangphan
 */
public class AdminDashboardPage2 extends javax.swing.JFrame {

	/**
	 * Creates new form AdminDashboardPage2
	 */
	public AdminDashboardPage2() {
		initComponents();
		
		displayProductsInProductsTable();
	}
	
	public void clearTableData() {
		DefaultTableModel model = (DefaultTableModel) productsTable.getModel();
		model.setRowCount(0);
	}
	
	static class ImageRenderer extends JLabel implements TableCellRenderer {
        public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
            if (value instanceof ImageIcon) {
                setIcon((ImageIcon) value);
            } else {
                setIcon(null);
            }
            return this;
        }
    }
    
	public void supportRenderImageInTheOrderProductsTable() {
		productsTable.getColumnModel().getColumn(3).setCellRenderer(new ImageRenderer());
	}
    
	public void displayProductsInProductsTable() {
		ProductService productService = new ProductService();
		OrderProductService orderProductService = new OrderProductService();
		ArrayList<Product> products = productService.getProducts();
		List<OrderProductResult> orderProductResults = orderProductService.getTotalMoneyPerDayPerProduct();
		DefaultTableModel model = (DefaultTableModel) productsTable.getModel();
		
		supportRenderImageInTheOrderProductsTable();
		int rowHeight = 150;
		productsTable.setRowHeight(rowHeight);
		
		for (OrderProductResult orderProductResult: orderProductResults) {
			ImageIcon scaledImageIcon = createScaledImageIcon(orderProductResult.getProductImage(), 120, 120);
			
			Object[] rowData = { orderProductResult.getOrderDay(), orderProductResult.getProductName(), orderProductResult.getTotalMoneyPerDayPerProduct(), scaledImageIcon };
			model.addRow(rowData);
		}
	}
    
	private ImageIcon createScaledImageIcon(byte[] imageData, int width, int height) {
	    ImageIcon imageIcon = new ImageIcon(imageData);
	    Image scaledImage = imageIcon.getImage().getScaledInstance(width, height, Image.SCALE_SMOOTH);
	    return new ImageIcon(scaledImage);
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jScrollPane3 = new javax.swing.JScrollPane();
                productsTable = new javax.swing.JTable();
                jButton1 = new javax.swing.JButton();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

                productsTable.setModel(new javax.swing.table.DefaultTableModel(
                        new Object [][] {

                        },
                        new String [] {
                                "Ngày", "Tên sản phẩm", "Tổng doanh thu", "Hình"
                        }
                ));
                productsTable.setSize(new java.awt.Dimension(450, 164));
                productsTable.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                productsTableMouseClicked(evt);
                        }
                });
                jScrollPane3.setViewportView(productsTable);

                jButton1.setText("Đồng bộ dữ liệu");
                jButton1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton1ActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane3)
                                .addContainerGap())
                        .addGroup(layout.createSequentialGroup()
                                .addGap(423, 423, 423)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(328, Short.MAX_VALUE))
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 581, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                );

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void productsTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productsTableMouseClicked
                int selectedRowIndex = productsTable.getSelectedRow();
//                int productId = (int) hehe.getValueAt(selectedRowIndex, PRODUCT_ID_COLUMN_POSITION);
//                Product product = productService.getProductById(productId);
//                addToTable(product);
        }//GEN-LAST:event_productsTableMouseClicked

        private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
		clearTableData();
		displayProductsInProductsTable();
        }//GEN-LAST:event_jButton1ActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(AdminDashboardPage2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(AdminDashboardPage2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(AdminDashboardPage2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(AdminDashboardPage2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new AdminDashboardPage2().setVisible(true);
			}
		});
	}

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton jButton1;
        private javax.swing.JScrollPane jScrollPane3;
        private javax.swing.JTable productsTable;
        // End of variables declaration//GEN-END:variables
}
